package halotukozak.regex

import scala.annotation.{publicInBinary, tailrec}
import scala.collection.immutable.{Queue, SortedSet}
import scala.quoted.{Expr, Quotes, ToExpr, Varargs}

/**
 * Compile-time counterpart to `regex"..."` (see [[Regex]]), but for a whole priority-ordered
 * pattern list instead of a single pattern: parses every pattern *and* builds the DFA
 * (`TokenMatcher.compile`'s derivative-state BFS) at macro-expansion time, splicing the
 * already-built matcher through the existing `given ToExpr[TokenMatcher]` as plain `Array[Int]`
 * tables. Without this, `TokenMatcher.fromRegexes`/`fromSubsets` re-derive that whole automaton
 * (BFS over derivative states, transition-table construction) from scratch on every process
 * startup, even though a literal, fixed pattern list (e.g. a lexer's token table) is exactly as
 * knowable at compile time as a single `regex"..."` pattern is.
 *
 * Every pattern must itself reduce to a literal `String` constant - a `Varargs` element that
 * doesn't is a macro-expansion error, not a runtime-parsing fallback: unlike `regex"..."`
 * (which falls back to parsing at runtime when the pattern isn't a literal, since there's
 * exactly one `Regex` either way), there's no equally sensible fallback for a whole vararg
 * pattern list threaded through a macro parameter - `TokenMatcher.fromRegexes`/`fromSubsets`
 * already exist as the explicit runtime-parsing entry point for patterns not known until
 * runtime (e.g. loaded from a config file).
 *
 * `patterns` must be declared `inline` too, for the same reason `regex"..."`'s `sc` receiver
 * is (see that doc comment): without it, the compiler binds the vararg call-site arguments to
 * a synthetic proxy val before splicing, so `'patterns` inside [[tokenMatcherImpl]] sees only a
 * reference to that val - never the literal argument list itself - and every call falls into
 * the "not a literal" branch below regardless of what was actually written at the call site.
 */
inline def tokenMatcher(inline patterns: String*): TokenMatcher = ${ tokenMatcherImpl('patterns) }

private def tokenMatcherImpl(patternsExpr: Expr[Seq[String]])(using quotes: Quotes): Expr[TokenMatcher] =
  import quotes.reflect.*
  patternsExpr match
    case Varargs(patternExprs) =>
      val regexes = patternExprs.map { patternExpr =>
        patternExpr.value match
          case None =>
            report.errorAndAbort("tokenMatcher patterns must be string literals known at compile time", patternExpr)
          case Some(pattern) =>
            RegexParser.parse(pattern) match
              case Left(error) => report.errorAndAbort(s"Regex parse error: $error", patternExpr)
              case Right(regex) => regex
      }
      Expr(TokenMatcher.fromRegexes(regexes*))
    case _ =>
      report.errorAndAbort("tokenMatcher requires a literal, statically-known list of pattern strings", patternsExpr)

/**
 * Lexer-style longest-match tokenizer over a priority-ordered list of patterns.
 *
 * Backed by a DFA obtained via Brzozowski-derivative subset construction over all patterns
 * in parallel (a single automaton, not one-per-pattern): building it walks the derivative
 * state space once (`fromRegexes`/`fromSubsets`), so `matchAt` itself is just array lookups -
 * a binary search to classify the current code point into an alphabet partition, then an
 * `Int` transition-table read - with no `Regex`/`Subset` allocation or derivation on the hot
 * path. Ties broken by lowest priority index (i.e., the first pattern in the input list wins).
 *
 * `boundaries(i)` is the first code point of partition `i` (`boundaries(0) == 0`); the
 * partition itself spans `[boundaries(i), boundaries(i + 1))`, with `boundaries.length` acting
 * as the exclusive upper partition for the last one. All derivative states share this same
 * partition: deriving only ever discards `Chars` leaves (via smart-constructor normalization),
 * never introduces new ones, so the alphabet fixed at the initial patterns already bounds
 * every reachable state.
 *
 * `transitions` is `numStates * boundaries.length` entries, row-major by state; `-1` marks the
 * (unrepresented) dead state, i.e. every pattern's derivative going empty.
 *
 * `accept(state)` is the lowest pattern index nullable in that state, or `-1` if none is.
 *
 * Constructor kept private - the only place that ever builds one directly is `compile` below,
 * in the companion object; `@publicInBinary` exists solely so `given ToExpr[TokenMatcher]`'s
 * quoted call to it still resolves once that quote is spliced into a different compilation
 * unit's generated bytecode (by `tokenMatcher(...)` below, or a user's own macro), despite
 * being `private` at the source level everywhere else.
 */
final class TokenMatcher @publicInBinary private (
  private val boundaries: Array[Int],
  private val transitions: Array[Int],
  private val accept: Array[Int],
):
  private def numPartitions: Int = boundaries.length

  /**
   * Match a token starting at `start` in `input`.
   *
   * @return `Some((priority, end))` where `priority` is the index of the winning
   *         pattern and `end` is the exclusive end of the longest match. `None` if
   *         no pattern matches any (possibly empty) prefix at `start`.
   */
  def matchAt(input: CharSequence, start: Int): Option[(priority: Int, end: Int)] =
    @tailrec
    def loop(state: Int, pos: Int, bestPriority: Int, bestEnd: Int): Option[(priority: Int, end: Int)] =
      if pos >= input.length then endResult(bestPriority, bestEnd)
      else
        val c = Character.codePointAt(input, pos)
        val next = transitions(state * numPartitions + TokenMatcher.partitionIndex(boundaries, c))
        if next < 0 then endResult(bestPriority, bestEnd)
        else
          val nextPos = pos + Character.charCount(c)
          accept(next) match
            case acc if acc >= 0 => loop(next, nextPos, acc, nextPos)
            case _ => loop(next, nextPos, bestPriority, bestEnd)
    def endResult(priority: Int, end: Int) = if end >= 0 then Some((priority = priority, end = end)) else None
    val initialAccept = accept(0)
    loop(0, start, initialAccept, if initialAccept >= 0 then start else -1)

  /** First position `>= from` at which some pattern matches a non-empty prefix. */
  def findFirst(input: CharSequence, from: Int): Option[(start: Int, priority: Int, end: Int)] =
    TokenMatcher
      .codePointStarts(input, from)
      .map(start => (start, matchAt(input, start)))
      .collectFirst:
        case (start, Some((priority, end))) if end > start => (start, priority, end)

object TokenMatcher:

  /** Build a matcher from pre-parsed regexes (use this from macros after compile-time parsing). */
  def fromRegexes(initial: Regex*): TokenMatcher = fromSubsets(initial.map(Subset.of)*)

  /** Build a matcher from pre-parsed subsets (use this from macros after compile-time parsing). */
  def fromSubsets(initial: Subset*): TokenMatcher = compile(initial)

  private def compile(patterns: Seq[Subset]): TokenMatcher =
    val boundaries = SortedSet(0, CharSet.maxCodePoint + 1)
      .concat(patterns.iterator.flatMap(_.underlying.alphabetBoundaries))
      .init
      .toArray

    def isDead(state: Seq[Subset]): Boolean = state.forall(_ == Subset.empty)

    /**
     * Derives `state` across every alphabet partition, assigning a fresh id (via `ids`) to any
     * not-yet-seen resulting state. `discovered` lists those newly-seen states, in partition
     * order, for the caller to enqueue for later exploration.
     */
    def deriveRow(
      state: Seq[Subset],
      ids: Map[Seq[Subset], Int],
    ): (row: Vector[Int], ids: Map[Seq[Subset], Int], discovered: List[Seq[Subset]]) =
      boundaries.indices.foldLeft((row = Vector.empty[Int], ids = ids, discovered = List.empty[Seq[Subset]])):
        case ((row, ids, discovered), i) =>
          val next = state.map(_.derive(boundaries(i)))
          if isDead(next) then (row = row :+ -1, ids = ids, discovered = discovered)
          else
            ids.get(next) match
              case Some(id) => (row = row :+ id, ids = ids, discovered = discovered)
              case None =>
                val id = ids.size
                (row = row :+ id, ids = ids.updated(next, id), discovered = discovered :+ next)

    @tailrec
    def loop(
      queue: Queue[Seq[Subset]],
      ids: Map[Seq[Subset], Int],
      transitions: Vector[Int],
      accept: Vector[Int],
    ): (transitions: Array[Int], accept: Array[Int]) =
      queue.dequeueOption match
        case None => (transitions = transitions.toArray, accept = accept.toArray)
        case Some((state, rest)) =>
          val (row, newIds, discovered) = deriveRow(state, ids)
          loop(rest.enqueueAll(discovered), newIds, transitions ++ row, accept :+ firstNullable(state))

    val (transitions, accept) = loop(Queue(patterns), Map(patterns -> 0), Vector.empty, Vector.empty)
    new TokenMatcher(boundaries, transitions, accept)

  private def firstNullable(state: Seq[Subset]): Int =
    state.iterator.zipWithIndex.collectFirst { case (sub, idx) if sub.nullable => idx }.getOrElse(-1)

  /** Largest `i` with `boundaries(i) <= c`; well-defined since `boundaries(0) == 0 <= c` always. */
  private def partitionIndex(boundaries: Array[Int], c: Int): Int =
    @tailrec
    def loop(lo: Int, hi: Int): Int =
      if lo == hi then lo
      else
        val mid = (lo + hi + 1) >>> 1
        if boundaries(mid) <= c then loop(mid, hi) else loop(lo, mid - 1)
    loop(0, boundaries.length - 1)

  /** Iterator of code-point start offsets in `input`, beginning at `from`. */
  private def codePointStarts(input: CharSequence, from: Int): Iterator[Int] =
    Iterator
      .iterate(from)(p => p + Character.charCount(Character.codePointAt(input, p)))
      .takeWhile(_ < input.length)

  // $COVERAGE-OFF$
  /** Embeds the already-built DFA table as `Array[Int]` literals - no `Regex`/`Subset` involved. */
  given ToExpr[TokenMatcher]:
    def apply(m: TokenMatcher)(using Quotes): Expr[TokenMatcher] =
      '{ TokenMatcher(${ Expr(m.boundaries) }, ${ Expr(m.transitions) }, ${ Expr(m.accept) }) }
  // $COVERAGE-ON$
